### ISSUE TITLE
Experiment with jar-with-dependencies

### ISSUE THREAD

**Issue by mvysny** [mvysny/vaadin-boot-example-maven#2]
Along the zip file, also create a jar-with-dependencies as described at https://www.baeldung.com/executable-jar-with-maven . 

Akin to Spring Boot, the jar would contain other jars as dependencies packaged inside. That solves the limitations of uberjar (unpack all dependencies then zip it into one huge jar) which disallows duplicate resources (such as `META-INF/MANIFEST.MF` and service loader config files).

**Comment by mvysny** [comment]
jar-with-dependencies only creates an uberjar again. Not what we needed. Closing as won't fix.

For the record, this is the Maven assembly plugin configuration:

```xml
            <plugin>
                <artifactId>maven-assembly-plugin</artifactId>
                <version>3.2.0</version>
                <configuration>
                    <archive>
                        <manifest>
                            <mainClass>com.vaadin.starter.skeleton.Main</mainClass>
                        </manifest>
                    </archive>
                    <descriptors>
                        <descriptor>src/main/assembly/zip.xml</descriptor>
                    </descriptors>
                    <descriptorRefs>
                        <descriptorRef>jar-with-dependencies</descriptorRef>
                    </descriptorRefs>
                </configuration>
                <executions>
                    <execution>
                        <id>make-assembly</id>
                        <phase>package</phase>
                        <goals>
                            <goal>single</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
```

**Comment by Osiris-Team** [comment]
@mvysny if we use such a duplicate transitive dependency in the project, which version will be picked if there are multiple in the zip?
